language: rust
sudo: required

rust:
  - nightly
  - beta
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build
  - travis-cargo doc
after_success:
  - travis-cargo doc-upload

env:
  global:
    secure: xsWR1FHBIJRYOv17p0o6RrwHPDE4spcqzsIj/wmPdWDbslplvCp9HiLyMNy7IAkCehhvXlgNerOByyw+VY52cYEQ+rzKeU8NMgI2tzg0If2KRoEKQd/MWN1avOwH511x4Qrtwh32jL1X553UVFnLcPWvdaWcByYJHfprw7IbPmo=
